### ISSUE TITLE
Should I commit .happypack folder to version control?

### ISSUE THREAD

**Issue by yhjor1212** [amireh/happypack#103]
Here is the result of running ten times locally with happypack enabled (in ms):

47349
20827
32435
22967
20572
18457
17984
19034
18496
25159

and I would like to use it on production. However, we are doing many split testing on different servers, it would be better to have .happypack folder on each repo to boost the build time.

I also observed that the first time are always slower. How can I use happypack to optimize if there is only single build on each server? Or happypack is just designed to optimize the non-first-build performance?

**Comment by amireh** [comment]
So, the first time is always slower because I'm assuming there's no cache yet (i.e. `.happypack` isn't populated). How long does a webpack build normally take **without** happypack?

You may gain more speed on the initial build if you tune the thread count, or use a threadpool if you're using multiple happypack instances.

Otherwise, maybe you can do the build once then share the `.happypack` folder on all servers so that they all have a valid cache and don't need to build the assets again?

I know others have tried sharing the cache. You may end up with a path-related issue since right now happypack's cache contains full filepaths of the files, so if those change from one server to another the cache won't be valid, but we can solve that if it's the case.

**Comment by yhjor1212** [comment]
I actually mean even if there is a cache (.happypack) exist, the first build time is still the slowest. Btw, thanks for answering.

**Comment by amireh** [comment]
Does it say that it's using items from the cache? Or does it say that N items are stale (where N would be your module count)?

Can you show the output of webpack with happypack please?
