### ISSUE TITLE
babel-loader not picking up .babelrc

### ISSUE THREAD

**Issue by eisisig** [amireh/happypack#11]
Nice project!

Was going to try it but got into troubles with babel loader. It seems that it isn't picking up .babelrc. Any ideas before I investigate?

I have extensive babel config so I cant use a query String

**Comment by eisisig** [comment]
I'm not sure if my setup is wonky but I just added '?extends=./.babelrc' as query and it's picking it up. So safe for now

**Comment by amireh** [comment]
Glad you worked around it. But I think it's because happypack's "fake" loader context might not be providing the loader with something it needs to resolve the babelrc file (maybe something like `this.context`? I have to investigate)

FWIW, it might be faster to roll your own "bare" babel transformer with the babelrc options either inlined or at least cached between calls. The stock loader performs the babelrc resolving & loading on every call which isn't optimal.

**Comment by amireh** [comment]
Closing this as it seems to be working. Feel free to re-open if you find otherwise.
