### ISSUE TITLE
Does this slow down build on small projects?

### ISSUE THREAD

**Issue by misterfresh** [amireh/happypack#110]
The benchmarks show that this project helps reduce build time from 50 seconds down to 10 seconds on large projects.

But can it reduce build time in a small project, say from 5 seconds to 1 second? 

I would think starting 4 node processes would increase startup time a bit. I tried it on a very small project and it seems to build slower overall (especially because startup seems to take a bit longer).

Also related to build performance, since current Chrome supports all of ES2015, and webpack supports ES6 imports natively, would it speed up the build to remove the ES2015 preset from babel configuration?

**Comment by amireh** [comment]
> But can it reduce build time in a small project, say from 5 seconds to 1 second?
>
> I would think starting 4 node processes would increase startup time a bit. I tried it on a  very small project and it seems to build slower overall (especially because startup seems to take a bit longer).

You're right in that it will most likely be slower for smaller projects. There's a constant overhead to starting up of N threads and communicating between the master and slaves. In general,  the more modules to compile, the better the benefits.

From my experience, I started seeing benefits after the 300 module threshold. That would include vendor dependencies, for which using a DLL brings some nice boost as well.

> Also related to build performance, since current Chrome supports all of ES2015, and webpack supports ES6 imports natively, would it speed up the build to remove the ES2015 preset from babel configuration?

I would *assume* it to help, since most of the time is spent on babel transformations (for the projects I work on, at least.) And I know that certain transformations are much more complex than others and may require full passes over the AST, so if the preset includes any of those, removing it should help. If you can speed your loaders up, your build time should definitely show it.

I have personally not tried it with babel yet, but would like to when I get the time.

**Comment by misterfresh** [comment]
Thanks for the insight! I will leave happypack in the configuration but set enabled to false, then set it to true  when the project becomes large enough.
