### ISSUE TITLE
Initialize plugin instances in parallel

### ISSUE THREAD

**Issue by jhnns** [amireh/happypack#111]
When I profiled my build, I saw that the application was idling quite a long time at the beginning (in my project it was around 700ms). This is because happypack uses the `run` and the `watch-run` hook which is not executed in parallel. That means that webpack waits for each happypack instance to initialize which you can clearly see in the profile (in this artificial example we have three instances):

![profile sequential](https://github.com/jhnns/happypack-perf-test/raw/master/profile-sequential.jpg)

I made a quick-and-dirty test and tried to use the [`make` hook](http://webpack.github.io/docs/plugins.html#make-parallel) instead of the `run` hook (which is executed in parallel):

![profile parallel](https://github.com/jhnns/happypack-perf-test/raw/master/profile-parallel.jpg)

If you want to play around with that, you can take a look at [my example repo](https://github.com/jhnns/happypack-perf-test). Since I refactored happypack inside my node_modules, I can't commit that. But it's fairly easy to add that change to happypack since the `compiler` is already passed to `apply`. Of course you need to make sure that `start()` is not called multiple times in watch mode.

I haven't tested it thoroughly but wanted to propose that change to shorten the startup time.

**Comment by amireh** [comment]
TIL! Thanks @jhnns that's good to know. I'll play with this.

Now that I think about it, we could warm the thread pool up even before webpack starts since as of 3.0 the initialization of the threads got decoupled from webpack compiler registration.

Are you using the blink profiler after the profiling changes introduced by node 6? I remember when I started writing happypack I couldn't much meaningful profiling information, tried using node-inspector. This would help a lot.

**Comment by jhnns** [comment]
> Now that I think about it, we could warm the thread pool up even before webpack starts since as of 3.0 the initialization of the threads got decoupled from webpack compiler registration.

That makes totally sense :+1:

> Are you using the blink profiler after the profiling changes introduced by node 6?

Yes. Check out [the start script](https://github.com/jhnns/happypack-perf-test/blob/4ef028ea737b9d52816a68a7a681a9f7fa19da17/package.json#L7). This will print a chrome debugger URL into the console which you can use to start the debugger/profiler.

**Comment by jhnns** [comment]
BTW: Depending on your OS, this profile may look very different. When I was experimenting with child processes a lot, I remembered that Linux was way faster in spawning processes.

**Comment by amireh** [comment]
@jhnns any chance you could try out #112 and see if it has any benefit? I didn't see any tangible results on Linux and need some time to try out on OS X.

**Comment by jhnns** [comment]
I can see a slightly performance improvement in my test scenario. Both pictures show the same time span (<400ms):

***Before***
![bildschirmfoto 2016-12-16 um 01 22 03](https://cloud.githubusercontent.com/assets/781746/21247324/ee5f01a4-c32e-11e6-8c44-94ef01d0a1f7.jpg)

***After***
![bildschirmfoto 2016-12-16 um 01 20 45](https://cloud.githubusercontent.com/assets/781746/21247347/12c76b3a-c32f-11e6-9da1-ac2929ad22df.jpg)

In a real-world project I couldn't see any improvement :(. I suspect, that this change will have a greater effect, the more plugin instances you have.

**Comment by amireh** [comment]
Man, that's too bad. We can try on that redux project which uses many instances, see if there's any gain there.

I believe the biggest gain we'll get from further optimizations is in some webpack routines and in babel transformers. Personally, I'm gonna look into babel optimizations soon because I see you guys are working hard on optimizing webpack 2 which is great.

I'd also still like to integrate happypack into webpack core, but there's very little time on my hands. :disappointed:

**Comment by jhnns** [comment]
> I'd also still like to integrate happypack into webpack core, but there's very little time on my hands. 

This is definitely a goal on the long run. Happypack is really helpful as proof of concept in this regard. Unfortunately we have to figure out a way for loaders that rely on the `_compiler` instance. Maybe we could also keep these loaders inside the main thread for now.

**Comment by amireh** [comment]
Gonna close this since it's not as good as we had hoped and it's been a while
