### ISSUE TITLE
enabled = false does not work

### ISSUE THREAD

**Issue by aight8** [amireh/happypack#124]
```
Module build failed:   TypeError: Cannot read property 'hasChanged' of undefined
  
  - HappyPlugin.js:304 HappyPlugin.compileInBackground
    [frontend]/[happypack]/lib/HappyPlugin.js:304:18
  
  - HappyPlugin.js:239 HappyPlugin.compile
    [frontend]/[happypack]/lib/HappyPlugin.js:239:32
  
  - HappyLoader.js:34 Object.HappyLoader
    [frontend]/[happypack]/lib/HappyLoader.js:34:15
```

**Comment by amireh** [comment]
Thanks for reporting this. This must have been broken ever since we introduced shared thread pools. I'm actually not sure about the option anymore since it's not so simple to disable the plugin without avoiding the loader itself so I'll be revisiting this.

In the meantime I'm afraid you'll have to use code branching to enable/disable happypack. That's how we do it in fact, without using the enabled option. For example:

```javascript
function getJSLoaders(happified = false) {
  if (happified) {
    return [ 'happypack/loader?id=js' ]
  }
  else {
    return [ 'babel' ]
  }
}

var jsLoaders = process.env.HAPPY === '1' ? getJSLoaders(true) : getJSLoaders(false)

config.module.loaders = [{ test: /\.js/, loaders: jsLoaders }]
config.plugins = [
  new HappyPack({
    enabled: process.env.HAPPY === '1',
    loaders: getJSLoaders(false),
    ...
  })
]
```

The gist of it is to make sure that you won't be passing your sources to `happypack/loader` if happypack isn't enabled (we use `process.env.HAPPY === '1'` for a switch.)

**Comment by amireh** [comment]
In the light of the change in v4 that [drops the enabled flag](https://github.com/amireh/happypack/blob/master/CHANGELOG.md#400), this ticket is no longer applicable so I'll be closing it.
