### ISSUE TITLE
[Question]Why happypack load css by async?

### ISSUE THREAD

**Issue by NE-SmallTown** [amireh/happypack#202]
- open sourcemap
![image](https://user-images.githubusercontent.com/18418010/34466439-c44e80cc-ef0d-11e7-8b92-c0dbc5f49c67.png)

- close sourcemap
At first, when the browser download the html, there is no style tag in the head tag, so the screen just has plain html, after a few seconds, it add style to the head tag(i.e. asynchronous)

```
plugins:    [
    new HappyPack({
          id: 'happypack-devclient-css',
          verbose: false,
          threads: 4,
          loaders: [
            'style-loader',
            {
              path: 'css-loader',
              // Include sourcemaps for dev experience++.
              query: {
                ...cssLoaderQuery,
                sourceMap: true,
              },
            },
            'postcss-loader',
          ],
        })
]
module: {
   rules: [
      test: /\.css$/,
      include: [....],
      loaders: ['happypack/loader?id=happypack-devclient-css'],
   ]  
}
```

#### but if I don't use happypack(like below) in the `module.rules`, the css won't be load as async`

```
use: ExtractTextPlugin.extract({
   fallback: 'style-loader',
   use: [
       {
          loader: 'css-loader',
          query: {
              ...cssLoaderQuery,
              sourceMap: true,
           },
       },
       'postcss-loader',
   ],
})
```

![image](https://user-images.githubusercontent.com/18418010/34466390-30f34e76-ef0c-11e7-9b4e-1e85200f4ca6.png)

So the question is, use happypack delay the time of first paint, which is a little annoying, and cause us can't use performance panel of chrome devtools(because the render process is not correct). And how to solve this, thanks :)

**Comment by amireh** [comment]
I'm fairly certain this isn't on happypack's end since this is runtime behaviour. The only thing that could be going on is that happypack isn't passing the loader options that you intend, which doesn't seem to be the case here either.

I believe this is because of your use of ExtractTextPlugin - `style-loader` would normally inject the styles asynchronously (take this with a grain of salt, I only very rarely used it) whereas ExtractTextPlugin doesn't use that loader and instead injects plain `<style />` links into your HTML.

You have two options:

1. use extract-text with happypack
2. don't use happypack for css

For the first, there's [the example](https://github.com/amireh/happypack/tree/master/examples/extract-text-webpack-plugin) and [this comment](https://github.com/amireh/happypack/issues/14#issuecomment-208254692) that may help you out. It may be a hit-or-miss thing; it works for some people and doesn't for others, so try it and see.

Something like this possibly:

```javascript
use: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: [
    {
      loader: 'happypack?id=happypack-devclient-css'
    }
  ],
})
```

Let me know if that helps! Please update us when you get around to it.

**Comment by NE-SmallTown** [comment]
Thanks for your reply.

It seems that this is `style-loader`'s fault(I guess), because when i don't use happypack and ExtractTextPlugin i.e. : 

```
use: [
   'style-loader',
    {
      loader: 'css-loader',
      query: {
        ...cssLoaderQuery,
        sourceMap: true,
      },
    },
  'postcss-loader',
],
```

The css still be load as async.

And your workaround below also can't solve this:

```
use: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: [
    'happypack/loader?id=happypack-devclient-css'
  ],
})
```

after html loaded:

![image](https://user-images.githubusercontent.com/18418010/34474987-c24c22de-efc1-11e7-93cc-3891c702b647.png)

a few seconds, after style loaded:

![image](https://user-images.githubusercontent.com/18418010/34474996-e3e1c0de-efc1-11e7-8227-a7dd04991f16.png)

And by the way, before I usually used `style-loader` and never happen something like this, so i think this is also not `style-loader`'s fault

**Comment by NE-SmallTown** [comment]
Close for https://stackoverflow.com/questions/48056391/is-there-any-operation-will-cause-css-be-loaded-as-async-in-webpack
