### ISSUE TITLE
Apply HappyPack without loader specified

### ISSUE THREAD

**Issue by maysale01** [amireh/happypack#54]
Is it possible to invoke the HappyPack plugin on the default webpack JS loader? Not sure what loaders webpack is using internally do resolve the dependency tree from the entry, or if there is a way to invoke the default behavior as a loader.

For example, a DLL bundle:

```javascript
...
  entry: {
    'vendors': [getPath('vendors/entry.js')]
  },
  output: {
    filename: '[name].bundle.js',
    path: 'dist/vendors/',

    // The name of the global variable which the library's
    // require() function will be assigned to
    library: '[name]_lib',
  },
  plugins: [
    new webpack.DllPlugin({
      // The path to the manifest file which maps between
      // modules included in a bundle and the internal IDs
      // within that bundle
      path: 'dist/vendors/[name]-manifest.json',
      // The name of the global variable which the library's
      // require function has been assigned to. This must match the
      // output.library option above
      name: '[name]_lib'
    }),
    new HappyPack({ loaders: [ '??' ] })
  ]
...
```

**Comment by amireh** [comment]
There is no "default" loader; if you're not specifying a loader then no loaders are applied and happypack has nothing to do. The time that webpack spends in your case is resolving dependencies and working its magic (not the loader magic, which is what happypack helps with).

Sorry. 😞

I get it that vendor DLLs could take some time to build, but that's what DLLs are for - so you build them only once instead of every time. Optimizing other parts of webpack other than applying loaders is beyond the scope of a plugin, the way I see it.

**Comment by maysale01** [comment]
Agreed, just wanted to try and use all my resources when assembling the DLLs. I wasn't sure if Webpack had a 'default loader' because I know it has some default polyfills for require, etc. Figured it had to have a default "transformer" or something of the sort, but I guess it isn't exposed? Thanks for the response and the public contributions!

**Comment by amireh** [comment]
Yeah, I don't think it's a loader per se, but webpack does do things in its core like a loader would - it generates an AST, extracts data, munges that AST and emits a "webpackified" version of the source. So in essence your assumption is correct, but it can be considered a pre (or post, or both?) step to applying loaders.

I think the internal architecture for this is changing in webpack 2, so maybe we will revisit in the future to see what can be done.
