### ISSUE TITLE
Adding HappyPack caused all webpack module IDs to change

### ISSUE THREAD

**Issue by wbobeirne** [amireh/happypack#58]
Hey, loving the plugin and it seems to be working splendidly, but on my first run I found every file changed, and my webpack records file had every module ID shuffled around. Is there any reason HappyPack wouldn't respect an existing webpack records file?

If this is something I have to pay the piper on once, that's fine. I'm just worried that this ID shuffling will happen on future builds, and require me to cache bust my entire site even if I'm only altering one bundle.

Let me know if I can provide more information!

**Comment by amireh** [comment]
Hmm, this is interesting. In theory, the build output should be _equivalent_ but nothing dictates it to be _identical_ which I think is the issue here.

I *think* (and this is just a wild guess) that the order of modules tracked by webpack in happy mode changes because certain trees might get compiled faster which causes the dependency resolving process to yield the modules in a different order (even if eventually we end up compiling all the modules just like in the regular webpack mode.)

Hopefully my assumption is incorrect because if it is correct then I'm not sure how we can guarantee or preserve the order in which modules or their dependency trees are handled (and thus the generated IDs).

Can you experiment by trying to re-run happypack (with no cache and artifacts or clear it between runs with `rm -r .happypack/`) and see if the output differs between a build and another?

I can try it on a real project myself since the examples here might not show the issue as they have a small number of modules but it'd be nice to see what you get as well.

Thanks for reporting and I'm glad the plugin is proving useful to you! :smile:

**Comment by amireh** [comment]
This makes me wonder if webpack has an existing plugin to enforce (re)ordering of modules based on the dependency graph and not the default module insertion order. That can be done as a post-processor (think the `-p` flag) and should solve this. It probably does, as webpack seems to have a solution for every problem in the world (mebbe except people invading us in the middle east, but perhaps webpack 3.0 will change that too! :trollface:)

**Comment by wbobeirne** [comment]
That was my concern as well, given its async nature. The way I conducted this experiment was to run webpack, `git add` the files, `rm -r .happypack`, and then run again to see any changes. I did not see any changes with an identical config, nor when I changed the thread counts for my happypack plugins trying to coax out any race conditions. So as far as I can tell, on one machine, happypack seems to have consistent module IDs.

`webpack.optimize.OccurrenceOrderPlugin` should enforce that, as it takes the most commonly referenced modules and gives them the lowest number to try to save a few bytes here and there. Unfortunately this does not seem to do the trick, as my production assets were already using this plugin, and they too are getting module ID changes.

**Comment by wbobeirne** [comment]
Ah god I'm a total idiot and hit send before I fully investigated the problem. The issue is that the records file keys modules by their loaders as well. The same file run through 2 different loaders might produce different results. So while my old keys were
```
"node_modules/babel-loader/index.js!node_modules/eslint-loader/index.js!my/example/js.js": 14,
```
they're now
```
"node_modules/happypack/loader.js?id=babel!node_modules/happypack/loader.js?id=eslint!my/example/js.js": 832,
```
So it looks like I'll need to delete my webpack.records.json file (To relinquish the smaller IDs claimed by the old keys) and re-run webpack once to get a new set of IDs, and it won't bother me again.

**Comment by amireh** [comment]
:grin: glad it's a false alarm. By the way, you don't need to use two happy plugin instances for two loaders! Change this:

```
"node_modules/happypack/loader.js?id=babel!node_modules/happypack/loader.js?id=eslint!my/example/js.js": 832,
```

to:

```
"node_modules/happypack/loader.js!my/example/js.js": 832,
```

Then in your plugin config just list both `eslint` and `babel`:

```javascript
plugins: [
  new HappyPack({ loaders: [ 'babel', 'eslint' ] })
]
```

This will most likely be faster.
