### ISSUE TITLE
Changing the loaders on a HappyPack plugin should invalidate the cache

### ISSUE THREAD

**Issue by wbobeirne** [amireh/happypack#74]
Ran in to an issue where I'm dynamically adding the `react-hot-loader` to my jsx-focused HappyPack plugin, but the happypack cache seems to keep around whichever ran first, instead of invalidating the cache. Here's the part of my config that makes the plugin:

```
const HappyPackPlugin = require("happypack");

const jsxLoaders = ["babel"];
if (isServer) {
    jsxLoaders.unshift("react-hot");
}

const jsxPlugin = new HappyPackPlugin({
    id: "babel",
    threads: 2,
    loaders: jsxLoaders,
    verbose: !isDashboard && !isTesting,
});

const jsxLoader = {
    // Babel
    test: /\.jsx?$/,
    loader: "happypack/loader?id=babel",
};

// These are added to the exported config...
```

If I run a command that has `isServer` as true first, and `react-hot-loader` gets added, if I later run a command that is meant to compile and not serve the JS, it'll get react-hot-loader code inside of my bundle. I can mitigate this by also making the HappyPackPlugin's id a variable that changes in the `isServer` conditional, but I think this is really nuanced behavior that should be accounted for, and could easily trip someone up.

I also wonder if this has any relation to #43, since I'm sure this dynamic `react-hot-loader` usage is pretty common in people's webpack configs.

**Comment by wbobeirne** [comment]
Mmm, this was exacerbated by the fact that I also had eslint running as a preloader. It looks like even when I was disabling the cache on the jsx happypack plugin, having an eslint plugin running separately and before it was causing those cached files to get used anyway. Not sure if I would classify that as a bug that could / should be fixed by happypack, or if that was a nuanced part of my config that I need to address myself. I'll leave this issue up and let @amireh decide, I'm happy to provide any additional info or make a simple example of this issue if needed.

**Comment by amireh** [comment]
So is it when you undefine the pre/post loaders, the cache is busted as expected?

The code is meant to invalidate the cache if either the `cacheContext` or the `loaders` list differs (internally, it just creates an aggregate context based on those two items) so I suspect that is not the issue. However, it does _not_ account for preLoader or postLoader entries since it doesn't see them, which might be what's happening here.

If that assumption is correct, one way to do this is to tell the happypack plugin about it in the `cacheContext` variable (e.g. pass `cacheContext: { isServer: isServer }`). That should make it invalidate the cache based on the value of `isServer`.

If you want to keep using a cache, you can instruct it to use a different `cachePath` based on the build type. We do this primarily based on NODE_ENV so that we keep a cache for development and test builds.

Let me know what you find out about pre/post loaders and then we can re-visit this.

**Comment by wbobeirne** [comment]
Yep, the `cacheContext` fix did the trick. I had tried it before to no avail, but that's because I had to add the `cacheContext` to both my babel HappyPack plugin AND my eslint HappyPack plugin. So yeah, it looks like it's an issue with not having any invalidation across pre / post loaders. I'm not sure what the best way around that would be without being explicit in the configuration. Perhaps each instance of the HappyPack plugin should maintain its own file cache, and not share? That might be slower for some configurations, but would ensure that this doesn't happen accidentally.

The cachePath strategy seems like it could be a viable option as well, thanks for the idea!

**Comment by amireh** [comment]
That's great to hear.

Should we consider this fixed or do you propose a change or something we can improve around this?

**Comment by wbobeirne** [comment]
A potential fix for this would be to "salt" the happypack cached file names with the id of the plugin. Right now there are different `cache--${id}.json` files for each id, but the file name references end up being the same. If the files were `s--${id}--${hash}` or `${id}/s--${hash}` instead of just `s--${hash}`. That way there'd be no overlap in the caches for each individual process, though some people might have liked the potential speed boosts as a result of that overlap.

**Comment by amireh** [comment]
In the light of the change in v4 that drops caching from happypack, this ticket is no longer applicable so I'll be closing it. Please feel free to re-open if the issue persists (i.e. it's not related to caching.)
